# Generated by Django 4.1.4 on 2023-01-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0006_delete_user'),
        ('Users', '0002_remove_trickster_user_learnedtricks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='LearnedTricks',
            field=models.ManyToManyField(blank=True, related_name='learned_trick', to='TricksterMain.trick'),
        ),
    ]
