# Generated by Django 4.1.4 on 2023-01-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0007_trick_programmes'),
        ('Users', '0003_alter_user_profile_learnedtricks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='CurrentlyLearningProgrammes',
            field=models.ManyToManyField(blank=True, related_name='currently_learning_programmes', to='TricksterMain.trick'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='SavedProgrammes',
            field=models.ManyToManyField(blank=True, related_name='saved_programmes', to='TricksterMain.trick'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='SavedTricks',
            field=models.ManyToManyField(blank=True, related_name='saved_trick', to='TricksterMain.trick'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='ProfilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
    ]
