# Generated by Django 4.1.4 on 2023-02-13 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_user_profile_currentlylearningprogrammes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='Bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='UserLevelProgress',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
