# Generated by Django 4.1.4 on 2023-02-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0012_programme_lesson_lessonnumber'),
        ('Users', '0007_user_profile_bio_user_profile_userlevelprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='CompletedLessons',
            field=models.ManyToManyField(blank=True, related_name='completed_lessons', to='TricksterMain.programme_lesson'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='CompletedProgrammes',
            field=models.ManyToManyField(blank=True, related_name='completed_programme', to='TricksterMain.trick_programme'),
        ),
    ]
