# Generated by Django 4.1.4 on 2023-03-29 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0018_remove_quiz_question_questionquiz_and_more'),
        ('Users', '0008_user_profile_completedlessons_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='UserLevelProgress',
            new_name='LevelProgress',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='UserDifficultyLevel',
            new_name='MasteryLevel',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='completed_skill_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='SkillLevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TricksterMain.skilllevel'),
        ),
    ]
