# Generated by Django 4.1.4 on 2023-04-02 14:13

import Users.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0018_remove_quiz_question_questionquiz_and_more'),
        ('Users', '0009_rename_userlevelprogress_user_profile_levelprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='Bio',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='SkillLevel',
            field=models.ForeignKey(blank=True, default=Users.models.get_default_skill_level, null=True, on_delete=django.db.models.deletion.CASCADE, to='TricksterMain.skilllevel'),
        ),
    ]
