# Generated by Django 4.1.4 on 2023-04-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_user_profile_bio_alter_user_profile_skilllevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trickster_user',
            name='Username',
            field=models.CharField(max_length=16, unique=True, verbose_name='Username'),
        ),
    ]
