# Generated by Django 4.1.5 on 2023-03-13 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0008_user_profile_completedlessons_and_more'),
        ('TricksterMain', '0018_remove_quiz_question_questionquiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_Section',
            fields=[
                ('SectionID', models.AutoField(primary_key=True, serialize=False)),
                ('SectionName', models.CharField(max_length=25)),
                ('SectionDiscription', models.TextField(blank=True)),
                ('SectionNoOfQuestions', models.IntegerField()),
                ('SectionType', models.CharField(choices=[('tricks', 'tricks'), ('terms', 'terms')], max_length=6)),
                ('SectionFailScore', models.IntegerField()),
                ('SectionPassScore', models.IntegerField()),
                ('SectionNumber', models.IntegerField()),
                ('SectionImg', models.ImageField(blank=True, null=True, upload_to='images/quiz_images')),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
        migrations.CreateModel(
            name='Skill_Level_Quiz',
            fields=[
                ('QuizID', models.AutoField(primary_key=True, serialize=False)),
                ('QuizTitle', models.CharField(max_length=25)),
                ('QuizDiscription', models.TextField(blank=True)),
                ('QuizNoOfSections', models.IntegerField()),
                ('QuizImg', models.ImageField(blank=True, null=True, upload_to='images/quiz_images')),
            ],
            options={
                'verbose_name_plural': 'Skill Level Quizes',
            },
        ),
        migrations.CreateModel(
            name='Term_Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BonusName', models.CharField(max_length=25)),
                ('BonusNoOfTerms', models.IntegerField()),
                ('BonusImg', models.ImageField(blank=True, null=True, upload_to='images/quiz_images')),
                ('BonusSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_questions', to='TricksterQuiz.quiz_section')),
            ],
            options={
                'verbose_name_plural': 'Term Bonuses',
            },
        ),
        migrations.CreateModel(
            name='Section_Trick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrickValue', models.IntegerField(choices=[(1, 1), (2, 2), (4, 4), (8, 8), (16, 16), (32, 32)])),
                ('Trick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_tricks', to='TricksterMain.trick')),
                ('TrickSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='TricksterQuiz.quiz_section')),
            ],
        ),
        migrations.CreateModel(
            name='Section_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrickScore', models.FloatField()),
                ('BonusScore', models.FloatField()),
                ('ResultBonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus', to='TricksterQuiz.term_bonus')),
                ('ResultSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='TricksterQuiz.quiz_section')),
                ('ResultUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='Users.user_profile')),
            ],
        ),
        migrations.AddField(
            model_name='quiz_section',
            name='SectionQuiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='TricksterQuiz.skill_level_quiz'),
        ),
        migrations.CreateModel(
            name='Bonus_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionText', models.CharField(max_length=200)),
                ('QuestionNumber', models.IntegerField()),
                ('QuestionImg', models.ImageField(blank=True, null=True, upload_to='images/quiz_images')),
                ('QuestionSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='TricksterQuiz.term_bonus')),
                ('QuestionTerm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_terms', to='TricksterMain.glossary_term')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnswerText', models.CharField(max_length=200)),
                ('AnswerCorrect', models.BooleanField(default=False)),
                ('AnswerQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='TricksterQuiz.bonus_question')),
            ],
        ),
    ]
