# Generated by Django 4.1.5 on 2023-03-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterQuiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus_answer',
            name='AnswerText',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bonus_question',
            name='QuestionText',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='quiz_section',
            name='SectionName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='skill_level_quiz',
            name='QuizTitle',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='term_bonus',
            name='BonusName',
            field=models.CharField(max_length=30),
        ),
    ]
