# Generated by Django 4.1.4 on 2023-03-29 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0018_remove_quiz_question_questionquiz_and_more'),
        ('TricksterQuiz', '0003_alter_quiz_section_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_section',
            name='SectionLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_level', to='TricksterMain.skilllevel'),
        ),
    ]
