# Generated by Django 4.1.4 on 2023-01-01 21:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLevels',
            fields=[
                ('SkillLevelID', models.AutoField(primary_key=True, serialize=False)),
                ('SkillLevelName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tricks',
            fields=[
                ('TrickID', models.AutoField(primary_key=True, serialize=False)),
                ('TrickName', models.CharField(max_length=25)),
                ('TrickDiscription', models.TextField(blank=True)),
                ('TrickHowTo', models.TextField(blank=True)),
                ('TrickDifficulty', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('TrickImgFileName', models.CharField(max_length=500)),
                ('TrickRecLevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TricksterMain.skilllevels')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=25)),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=500)),
                ('LearnedTricks', models.ManyToManyField(blank=True, to='TricksterMain.tricks')),
                ('SkillLevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TricksterMain.skilllevels')),
            ],
        ),
    ]
