# Generated by Django 4.1.4 on 2023-01-01 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillLevels',
            new_name='SkillLevel',
        ),
        migrations.RenameModel(
            old_name='Tricks',
            new_name='Trick',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
