# Generated by Django 4.1.4 on 2023-01-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0003_alter_trick_trickimgfilename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trick',
            name='TrickImgFileName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='PhotoFileName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
