# Generated by Django 4.1.4 on 2023-01-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0004_alter_trick_trickimgfilename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trick',
            name='TrickImgFileName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='PhotoFileName',
        ),
        migrations.AddField(
            model_name='trick',
            name='TrickImg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='ProfilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
