# Generated by Django 4.1.4 on 2023-01-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0005_remove_trick_trickimgfilename_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
