# Generated by Django 4.1.4 on 2023-01-23 23:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0006_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trick_Programmes',
            fields=[
                ('ProgrammeID', models.AutoField(primary_key=True, serialize=False)),
                ('ProgrammeName', models.CharField(max_length=25)),
                ('ProgrammeDiscription', models.TextField(blank=True)),
                ('ProgrammeDifficulty', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('ProgrammeImg', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ProgrammeRecLevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TricksterMain.skilllevel')),
                ('ProgrammeTricks', models.ManyToManyField(blank=True, related_name='programme_tricks', to='TricksterMain.trick')),
            ],
        ),
    ]
