# Generated by Django 4.1.4 on 2023-01-24 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_user_profile_currentlylearningprogrammes_and_more'),
        ('TricksterMain', '0007_trick_programmes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trick_Programmes',
            new_name='Trick_Programme',
        ),
    ]
