# Generated by Django 4.1.4 on 2023-02-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0008_rename_trick_programmes_trick_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='trick',
            name='TrickCategory',
            field=models.ManyToManyField(blank=True, related_name='trick_category_tags', to='TricksterMain.category'),
        ),
        migrations.AddField(
            model_name='trick_programme',
            name='ProgrammeCategory',
            field=models.ManyToManyField(blank=True, related_name='programme_category_tags', to='TricksterMain.category'),
        ),
    ]
