# Generated by Django 4.1.4 on 2023-02-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0009_category_trick_trickcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CategoryDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='CategoryImg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
