# Generated by Django 4.1.4 on 2023-02-13 17:22

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0010_category_categorydescription_category_categoryimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme_Lesson',
            fields=[
                ('LessonID', models.AutoField(primary_key=True, serialize=False)),
                ('LessonName', models.CharField(max_length=25)),
                ('LessonShortDesc', models.TextField(blank=True)),
                ('LessonLongDesc', models.TextField(blank=True)),
                ('LessonVideo', embed_video.fields.EmbedVideoField(blank=True)),
                ('Programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='TricksterMain.trick_programme')),
            ],
        ),
    ]
