# Generated by Django 4.1.4 on 2023-02-16 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0011_programme_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme_lesson',
            name='LessonNumber',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
