# Generated by Django 4.1.4 on 2023-02-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0014_glossary_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary_term',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
