# Generated by Django 4.1.4 on 2023-03-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0015_glossary_term_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
