# Generated by Django 4.1.5 on 2023-03-13 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0017_trickster_quiz_quiz_result_quiz_question_quiz_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_question',
            name='QuestionQuiz',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='QuizTricks',
        ),
        migrations.RemoveField(
            model_name='quiz_result',
            name='ResultQuiz',
        ),
        migrations.RemoveField(
            model_name='quiz_result',
            name='ResultUser',
        ),
        migrations.RemoveField(
            model_name='trickster_quiz',
            name='QuizTricks',
        ),
        migrations.DeleteModel(
            name='Quiz_Answer',
        ),
        migrations.DeleteModel(
            name='Quiz_Question',
        ),
        migrations.DeleteModel(
            name='Quiz_Result',
        ),
        migrations.DeleteModel(
            name='Trickster_Quiz',
        ),
    ]
