# Generated by Django 4.1.4 on 2023-04-02 22:12

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0018_remove_quiz_question_questionquiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='TrickVideo',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
