# Generated by Django 4.1.4 on 2023-04-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0019_trick_trickvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='SubmittedBy',
            field=models.IntegerField(null=True, verbose_name='Submitted By'),
        ),
        migrations.AddField(
            model_name='trick_programme',
            name='ProgrammeCreator',
            field=models.IntegerField(default=1, verbose_name='Programme Creator'),
        ),
    ]
