# Generated by Django 4.1.4 on 2023-04-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TricksterMain', '0020_trick_submittedby_trick_programme_programmecreator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trick',
            name='SubmittedBy',
        ),
        migrations.RemoveField(
            model_name='trick_programme',
            name='ProgrammeCreator',
        ),
        migrations.AddField(
            model_name='trick',
            name='SubmittedByID',
            field=models.IntegerField(null=True, verbose_name='Submitted By ID'),
        ),
        migrations.AddField(
            model_name='trick_programme',
            name='ProgrammeCreatorID',
            field=models.IntegerField(default=1, verbose_name='Programme Creator ID'),
        ),
    ]
